# ML-model1) iris 데이터셋 상세

### 1. 데이터셋 로드
+ 모듈 임포트: from sklearn.datasets import lodad_데이터셋명
+ 데이터셋 객체 생성: data = load_데이터셋명()

In [2]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


### 2. 데이터셋 키이름 확인
+ data.keys()

In [6]:
keys = iris_data.keys()
keys

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

키는 보통 data, target, target_names, feature_names, DESCR로 이루어져 있다. 
+ data: 피처의 데이터 세트
+ target: 분류 - 레이블 값. 회귀 - 숫자 결과값 데이터 세트
+ target_names: 개별 레이블의 이름
+ feature_names: 피처의 이름
+ DESCR: 데이터세트에 대한 설명, 각 피처의 설명

### 3. 데이터셋의 feature_names 확인

In [7]:
print("\n feature_names의 type: ", type(iris_data.feature_names))
print("\n feature_names의 shape: ", len(iris_data.feature_names))
print(iris_data.feature_names)


 feature_names의 type:  <class 'list'>

 feature_names의 shape:  4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


### 4. 데이터셋의 target_names 확인

In [16]:
print("\n target_names의 type: ", type(iris_data.target_names))
print("\n target_names의 shape: ", len(iris_data.target_names))
print(iris_data.target_names)


 target_names의 type:  <class 'numpy.ndarray'>

 target_names의 shape:  3
['setosa' 'versicolor' 'virginica']


### 5. 데이터셋 데이터 확인

In [17]:
print("\n data의 type: ", type(iris_data.data))
print("\n data의 shape: ", iris_data.data.shape)
print(iris_data['data'])


 data의 type:  <class 'numpy.ndarray'>

 data의 shape:  (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5. 

### 6. 데이터셋 target 확인

In [18]:
print("\n target의 type: ", type(iris_data.target))
print("\n target의 shape: ", iris_data.target.shape)
print(iris_data.target)


 target의 type:  <class 'numpy.ndarray'>

 target의 shape:  (150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
